In [1]:
import pandas as pd
import numpy as np
import statistics
import collections
import statsmodels
from fbprophet import Prophet

from statsmodels.tsa.arima_model import ARIMA
from statsmodels.tsa.arima.model import ARIMAResults

import hts
from hts import HTSRegressor
from hts.hierarchy import HierarchyTree

import pmdarima as pm


import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
# import the data files
data = pd.read_excel('./data.xlsx',sheet_name='Quadro', skiprows=11, usecols="A:D", header=None, index_col=0)

In [3]:
first_row = data.loc["Years",:]
data.columns=first_row
data.drop(data.index[[0]],inplace=True)

In [4]:
# lowercase the column names
data.columns = [col_name.lower() for col_name in data.columns]

In [5]:
# cleanup region name 
data["nutsiii"] = data["nutsiii"].apply(lambda x: x.replace(" ", "_"))

# map the full NUTSII names to abbreviations
nutsii_dict = {
    "Norte": "NT",
    "Centro": "CT",
    "Área Metropolitana de Lisboa": "LIS",
    "Alentejo": "ALT",
    "Algarve": "ALG",
    "Região Autónoma dos Açores": "AÇR",
    "Região Autónoma da Madeira": "MAD",
}

data["nutsii"] = data["nutsii"].map(nutsii_dict)

In [6]:
data.reset_index(inplace=True)
data.columns.values[0]="date"
data

          date nutsii                      nutsiii nº of nights
0   2009-12-31     NT                   Alto_Minho            0
1   2009-12-31     NT                       Cávado      515.714
2   2009-12-31     NT                          Ave      295.402
3   2009-12-31     NT  Área_Metropolitana_do_Porto            0
4   2009-12-31     NT                  Alto_Tâmega            0
..         ...    ...                          ...          ...
403 2020-12-31    AÇR                Ilha_do_Faial        44.39
404 2020-12-31    AÇR              Ilha_das_Flores       22.416
405 2020-12-31    AÇR                Ilha_do_Corvo        1.166
406 2020-12-31    MAD              Ilha_da_Madeira     2282.241
407 2020-12-31    MAD          Ilha_de_Porto_Santo      159.295

[408 rows x 4 columns]

## Ground Up Example
Make custom forecasts and reconciling them

In [7]:
# specifying levels in the hierarchy
level_names = ['nutsii', 'nutsiii']
#specifying the levels to include in the hierarchy structure
hier = [['nutsii'], ['nutsiii']]
#get a wide pandas.DataFrame with the individual time series to create forecasts.
wide_df, sum_mat, sum_mat_labels = hts.functions.get_hierarchichal_df(data,
                                                                      level_names=level_names,
                                                                      hierarchy=hier,
                                                                      date_colname='date',
                                                                      val_colname='nº of nights')

In [8]:
wide_df = pd.DataFrame(wide_df,
                    index=pd.date_range(end='2021-12', freq='A', periods=12),
                    columns=wide_df.columns)
wide_df

nutsii_nutsiii,ALG_Algarve,ALT_Alentejo_Central,ALT_Alentejo_Litoral,ALT_Alto_Alentejo,ALT_Baixo_Alentejo,ALT_Lezíria_do_Tejo,AÇR_Ilha_Graciosa,AÇR_Ilha_Terceira,AÇR_Ilha_das_Flores,AÇR_Ilha_de_Santa_Maria,...,Ilha_de_São_Miguel,Ilha_Terceira,Ilha_Graciosa,Ilha_de_São_Jorge,Ilha_do_Pico,Ilha_do_Faial,Ilha_das_Flores,Ilha_do_Corvo,Ilha_da_Madeira,Ilha_de_Porto_Santo
2009-12-31,12927.603,383.064,277.538,175.475,172.589,95.649,9.512,141.563,0,22.164,...,0.000,141.563,9.512,0.000,0.000,79.862,0.000,0.000,0.000,240.426
2010-12-31,13247.45,403.992,307.195,183.086,179.06,99.225,16.043,131.507,14.229,23.933,...,0.000,131.507,16.043,0.000,0.000,81.032,14.229,0.000,4776.315,217.210
2011-12-31,13979.866,411.336,376.595,189.742,167.212,98.767,16.449,140.675,15.8,23.122,...,0.000,140.675,16.449,0.000,0.000,75.845,15.800,0.000,5289.188,276.098
2012-12-31,14326.774,389.28,370.033,150.747,142.039,90.046,14.072,135.388,13.666,21.098,...,0.000,135.388,14.072,0.000,0.000,73.615,13.666,0.000,5260.374,247.311
2013-12-31,14741.969,0,349.377,0,132.437,85.383,10.943,146.948,13.136,21.061,...,0.000,146.948,10.943,0.000,0.000,77.054,13.136,0.000,0.000,288.579
2014-12-31,16591.548,551.628,521.154,235.487,231.904,124.123,12.714,150.665,0,24.033,...,755.397,150.665,12.714,0.000,49.584,89.556,0.000,0.000,6164.884,341.982
2015-12-31,17256.396,646.812,585.969,274.683,278.892,137.952,13.035,162.693,0,23.12,...,931.702,162.693,13.035,0.000,57.564,101.300,0.000,0.000,6648.445,381.581
2016-12-31,19005.838,725.546,669.363,299.251,295.075,145.078,16.204,263.329,0,26.146,...,1081.578,263.329,16.204,0.000,66.628,115.291,0.000,0.000,7447.071,483.837
2017-12-31,20207.151,829.956,787.602,346.116,337.508,186.203,16.626,294.117,0,28.623,...,1281.791,294.117,16.626,0.000,71.633,115.658,0.000,0.000,7845.518,514.471
2018-12-31,20443.247,898.853,864.051,382.257,350.619,180.165,16.194,322.97,36.918,28.844,...,1414.615,322.970,16.194,0.000,106.745,158.933,36.918,0.000,7849.500,494.766
2019-12-31,20900.495,934.873,978.415,430.424,384.617,210.501,17.595,316.442,38.406,31.199,...,1552.681,316.442,17.595,0.000,110.614,164.477,38.406,0.000,6997.213,459.984
2020-12-31,7890.711,481.199,692.694,291.685,251.857,111.82,7.544,114.805,22.416,15.136,...,391.962,114.805,7.544,17.003,39.954,44.390,22.416,1.166,2282.241,159.295

In [9]:
wide_df.index[0]

Timestamp('2009-12-31 00:00:00', freq='A-DEC')

In [10]:
# Create a DataFrame to store new forecasts in
# Here we just do an average
forecasts = pd.DataFrame(index=['forecast'], columns=wide_df.columns)

for col in wide_df.columns:
        forecasts[col] = statistics.mean(wide_df[col])
forecasts

nutsii_nutsiii,ALG_Algarve,ALT_Alentejo_Central,ALT_Alentejo_Litoral,ALT_Alto_Alentejo,ALT_Baixo_Alentejo,ALT_Lezíria_do_Tejo,AÇR_Ilha_Graciosa,AÇR_Ilha_Terceira,AÇR_Ilha_das_Flores,AÇR_Ilha_de_Santa_Maria,...,Ilha_de_São_Miguel,Ilha_Terceira,Ilha_Graciosa,Ilha_de_São_Jorge,Ilha_do_Pico,Ilha_do_Faial,Ilha_das_Flores,Ilha_do_Corvo,Ilha_da_Madeira,Ilha_de_Porto_Santo
forecast,15959.920667,554.711583,564.998833,246.579417,243.65075,130.409333,13.910917,193.425167,12.880917,24.039917,...,617.477167,193.425167,13.910917,1.416917,41.8935,98.084417,12.880917,0.097167,5046.729083,342.128333

In [11]:
#Store the forecasts in a dictionary to be passed to the reconciliation algorithm
pred_dict = collections.OrderedDict()
# Add predictions to dictionary in same order as summing matrix
for label in sum_mat_labels:
    pred_dict[label] = pd.DataFrame(data=forecasts[label].values, columns=['yhat'])

In [12]:
#Reconcile the forecasts.Here we use OLS optimal reconciliation. 
revised = hts.functions.optimal_combination(pred_dict, sum_mat, method='OLS', mse={})

#Then, put reconciled forecasts in the same wide DataFrame format.
revised_forecasts = pd.DataFrame(data=revised[0:,0:], index=forecasts.index, columns=sum_mat_labels)

In [13]:
revised_forecasts

,total,Ilha_de_Porto_Santo,Ilha_da_Madeira,Ilha_do_Corvo,Ilha_das_Flores,Ilha_do_Faial,Ilha_do_Pico,Ilha_de_São_Jorge,Ilha_Graciosa,Ilha_Terceira,...,AÇR_Ilha_de_São_Miguel,AÇR_Ilha_Terceira,AÇR_Ilha_Graciosa,AÇR_Ilha_de_São_Jorge,AÇR_Ilha_do_Pico,AÇR_Ilha_do_Faial,AÇR_Ilha_das_Flores,AÇR_Ilha_do_Corvo,MAD_Ilha_da_Madeira,MAD_Ilha_de_Porto_Santo
forecast,41885.808675,344.191664,5048.792414,0.847469,13.631219,98.834719,42.643802,2.167219,14.661219,194.175469,...,618.227469,194.175469,14.661219,2.167219,42.643802,98.834719,13.631219,0.847469,5048.792414,344.191664

## Reconcile Pre-Computed Forecasts Example

In [14]:
# create the bottom level data
data_bottom_level = data.pivot(index="date", columns="nutsii_nutsiii", values="nº of nights")

# create the middle level data
data_middle_level = data.groupby(["date", "nutsii"]).sum().reset_index(drop=False).pivot(index="date", columns="nutsii", values="nº of nights")

# create the total level data
data_total = data.groupby("date")["nº of nights"].sum().to_frame().rename(columns={"nº of nights": "total"})

In [15]:
# join the DataFrames
hierarchy_data = data_bottom_level.join(data_middle_level).join(data_total)
hierarchy_data.index = pd.to_datetime(hierarchy_data.index)

print(f"Number of time series at the bottom level: {data_bottom_level.shape[1]}")
print(f"Number of time series at the middle level: {data_middle_level.shape[1]}")

hierarchy_data

Number of time series at the bottom level: 34
Number of time series at the middle level: 7

,ALG_Algarve,ALT_Alentejo_Central,ALT_Alentejo_Litoral,ALT_Alto_Alentejo,ALT_Baixo_Alentejo,ALT_Lezíria_do_Tejo,AÇR_Ilha_Graciosa,AÇR_Ilha_Terceira,AÇR_Ilha_das_Flores,AÇR_Ilha_de_Santa_Maria,...,NT_Tâmega_e_Sousa,NT_Área_Metropolitana_do_Porto,ALG,ALT,AÇR,CT,LIS,MAD,NT,total
date,,,,,,,,,,,,,,,,,,,,,
2009-12-31,12927.603,383.064,277.538,175.475,172.589,95.649,9.512,141.563,0,22.164,...,0,0,12927.603,1104.315,253.101,1254.849,0.000,240.426,1026.364,16806.658
2010-12-31,13247.45,403.992,307.195,183.086,179.06,99.225,16.043,131.507,14.229,23.933,...,0,0,13247.450,1172.558,266.744,1254.948,0.000,4993.525,976.605,21911.83
2011-12-31,13979.866,411.336,376.595,189.742,167.212,98.767,16.449,140.675,15.8,23.122,...,0,0,13979.866,1243.652,271.891,1422.553,0.000,5565.286,966.599,23449.847
2012-12-31,14326.774,389.28,370.033,150.747,142.039,90.046,14.072,135.388,13.666,21.098,...,0,0,14326.774,1142.145,257.839,1367.118,0.000,5507.685,966.026,23567.587
2013-12-31,14741.969,0,349.377,0,132.437,85.383,10.943,146.948,13.136,21.061,...,0,0,14741.969,567.197,269.142,688.869,10040.808,288.579,756.368,27352.932
2014-12-31,16591.548,551.628,521.154,235.487,231.904,124.123,12.714,150.665,0,24.033,...,176.195,4030.435,16591.548,1664.296,1081.949,4486.949,12279.422,6506.866,6061.742,48672.772
2015-12-31,17256.396,646.812,585.969,274.683,278.892,137.952,13.035,162.693,0,23.12,...,220.657,4580.506,17256.396,1924.308,1289.414,5058.446,13468.659,7030.026,7001.899,53029.148
2016-12-31,19005.838,725.546,669.363,299.251,295.075,145.078,16.204,263.329,0,26.146,...,257.909,5210.981,19005.838,2134.313,1569.176,5643.792,14800.346,7930.908,7989.922,59074.295
2017-12-31,20207.151,829.956,787.602,346.116,337.508,186.203,16.626,294.117,0,28.623,...,291.477,5883.971,20207.151,2487.385,1808.448,6764.282,16695.206,8359.989,9008.846,65331.307
2018-12-31,20443.247,898.853,864.051,382.257,350.619,180.165,16.194,322.97,36.918,28.844,...,338.937,6319.435,20443.247,2675.945,2085.219,6777.827,17516.975,8344.266,9778.017,67621.496
2019-12-31,20900.495,934.873,978.415,430.424,384.617,210.501,17.595,316.442,38.406,31.199,...,376.289,7013.152,20900.495,2938.830,2231.414,7134.863,18639.062,7457.197,10810.712,70112.573
2020-12-31,7890.711,481.199,692.694,291.685,251.857,111.82,7.544,114.805,22.416,15.136,...,225.48,2319.572,7890.711,1829.255,654.376,3362.011,5254.354,2441.536,4366.056,25798.299

In [16]:
pd.date_range(end='2021-12', freq='A', periods=12)

DatetimeIndex(['2009-12-31', '2010-12-31', '2011-12-31', '2012-12-31',
               '2013-12-31', '2014-12-31', '2015-12-31', '2016-12-31',
               '2017-12-31', '2018-12-31', '2019-12-31', '2020-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')

In [17]:
hierarchy_data = pd.DataFrame(hierarchy_data, index=pd.date_range(end='2021-12', freq='A', periods=12), columns=hierarchy_data.columns)
hierarchy_data

,ALG_Algarve,ALT_Alentejo_Central,ALT_Alentejo_Litoral,ALT_Alto_Alentejo,ALT_Baixo_Alentejo,ALT_Lezíria_do_Tejo,AÇR_Ilha_Graciosa,AÇR_Ilha_Terceira,AÇR_Ilha_das_Flores,AÇR_Ilha_de_Santa_Maria,...,NT_Tâmega_e_Sousa,NT_Área_Metropolitana_do_Porto,ALG,ALT,AÇR,CT,LIS,MAD,NT,total
2009-12-31,12927.603,383.064,277.538,175.475,172.589,95.649,9.512,141.563,0,22.164,...,0,0,12927.603,1104.315,253.101,1254.849,0.000,240.426,1026.364,16806.658
2010-12-31,13247.45,403.992,307.195,183.086,179.06,99.225,16.043,131.507,14.229,23.933,...,0,0,13247.450,1172.558,266.744,1254.948,0.000,4993.525,976.605,21911.83
2011-12-31,13979.866,411.336,376.595,189.742,167.212,98.767,16.449,140.675,15.8,23.122,...,0,0,13979.866,1243.652,271.891,1422.553,0.000,5565.286,966.599,23449.847
2012-12-31,14326.774,389.28,370.033,150.747,142.039,90.046,14.072,135.388,13.666,21.098,...,0,0,14326.774,1142.145,257.839,1367.118,0.000,5507.685,966.026,23567.587
2013-12-31,14741.969,0,349.377,0,132.437,85.383,10.943,146.948,13.136,21.061,...,0,0,14741.969,567.197,269.142,688.869,10040.808,288.579,756.368,27352.932
2014-12-31,16591.548,551.628,521.154,235.487,231.904,124.123,12.714,150.665,0,24.033,...,176.195,4030.435,16591.548,1664.296,1081.949,4486.949,12279.422,6506.866,6061.742,48672.772
2015-12-31,17256.396,646.812,585.969,274.683,278.892,137.952,13.035,162.693,0,23.12,...,220.657,4580.506,17256.396,1924.308,1289.414,5058.446,13468.659,7030.026,7001.899,53029.148
2016-12-31,19005.838,725.546,669.363,299.251,295.075,145.078,16.204,263.329,0,26.146,...,257.909,5210.981,19005.838,2134.313,1569.176,5643.792,14800.346,7930.908,7989.922,59074.295
2017-12-31,20207.151,829.956,787.602,346.116,337.508,186.203,16.626,294.117,0,28.623,...,291.477,5883.971,20207.151,2487.385,1808.448,6764.282,16695.206,8359.989,9008.846,65331.307
2018-12-31,20443.247,898.853,864.051,382.257,350.619,180.165,16.194,322.97,36.918,28.844,...,338.937,6319.435,20443.247,2675.945,2085.219,6777.827,17516.975,8344.266,9778.017,67621.496
2019-12-31,20900.495,934.873,978.415,430.424,384.617,210.501,17.595,316.442,38.406,31.199,...,376.289,7013.152,20900.495,2938.830,2231.414,7134.863,18639.062,7457.197,10810.712,70112.573
2020-12-31,7890.711,481.199,692.694,291.685,251.857,111.82,7.544,114.805,22.416,15.136,...,225.48,2319.572,7890.711,1829.255,654.376,3362.011,5254.354,2441.536,4366.056,25798.299

In [18]:
hierarchy_data.index[0]

Timestamp('2009-12-31 00:00:00', freq='A-DEC')

In [19]:
#Creating the hierarchy
nutsii = data["nutsii"].unique()
nutsiii = data["nutsii_nutsiii"].unique()

total = {'total': list(nutsii)}
nutsii = {k: [x for x in nutsiii if x.startswith(k)] for k in nutsii}
hierarchy = {**total, **nutsii}

In [20]:
Htree = HierarchyTree.from_nodes(nodes=hierarchy, df=hierarchy_data)
Htree

- total
   |- NT
   |  |- NT_Alto_Minho
   |  |- NT_Cávado
   |  |- NT_Ave
   |  |- NT_Área_Metropolitana_do_Porto
   |  |- NT_Alto_Tâmega
   |  |- NT_Tâmega_e_Sousa
   |  |- NT_Douro
   |  - NT_Terras_de_Trás-os-Montes
   |- CT
   |  |- CT_Oeste
   |  |- CT_Região_de_Aveiro
   |  |- CT_Região_de_Coimbra
   |  |- CT_Região_de_Leiria
   |  |- CT_Viseu_Dão_Lafões
   |  |- CT_Beira_Baixa
   |  |- CT_Médio_Tejo
   |  - CT_Beiras_e_Serra_da_Estrela
   |- LIS
   |  - LIS_Área_Metropolitana_de_Lisboa
   |- ALT
   |  |- ALT_Alentejo_Litoral
   |  |- ALT_Baixo_Alentejo
   |  |- ALT_Lezíria_do_Tejo
   |  |- ALT_Alto_Alentejo
   |  - ALT_Alentejo_Central
   |- ALG
   |  - ALG_Algarve
   |- AÇR
   |  |- AÇR_Ilha_de_Santa_Maria
   |  |- AÇR_Ilha_de_São_Miguel
   |  |- AÇR_Ilha_Terceira
   |  |- AÇR_Ilha_Graciosa
   |  |- AÇR_Ilha_de_São_Jorge
   |  |- AÇR_Ilha_do_Pico
   |  |- AÇR_Ilha_do_Faial
   |  |- AÇR_Ilha_das_Flores
   |  - AÇR_Ilha_do_Corvo
   - MAD
      |- MAD_Ilha_da_Madeira
      - MAD_Ilha_de_Porto_Santo

In [21]:
sum_mat2, sum_mat_labels2 = hts.functions.to_sum_mat(Htree)

In [22]:
forecasts2 = pd.DataFrame(columns=hierarchy_data.columns, index=['forecast'])

In [23]:
 # Make forecasts made outside of hts package.
for col in hierarchy_data.columns:
    model = statsmodels.tsa.holtwinters.SimpleExpSmoothing(hierarchy_data[col].values).fit()
    fcst = list(model.forecast(1))
    forecasts2[col] = fcst

In [24]:
pred_dict2 = collections.OrderedDict()

In [25]:
# Add predictions to dictionary is same order as summing matrix
for label in sum_mat_labels2:
    pred_dict2[label] = pd.DataFrame(data=forecasts2[label].values, columns=['yhat'])

In [26]:
revised2 = hts.functions.optimal_combination(pred_dict2, sum_mat2, method='OLS', mse={})

In [27]:
# Put reconciled forecasts in nice DataFrame form
revised_forecasts2 = pd.DataFrame(data=revised2[0:,0:], index=forecasts2.index, columns=sum_mat_labels2)

In [28]:
revised_forecasts2

,total,MAD,AÇR,ALG,ALT,LIS,CT,NT,NT_Alto_Minho,NT_Cávado,...,AÇR_Ilha_de_São_Miguel,AÇR_Ilha_Terceira,AÇR_Ilha_Graciosa,AÇR_Ilha_de_São_Jorge,AÇR_Ilha_do_Pico,AÇR_Ilha_do_Faial,AÇR_Ilha_das_Flores,AÇR_Ilha_do_Corvo,MAD_Ilha_da_Madeira,MAD_Ilha_de_Porto_Santo
forecast,26461.383482,4606.500589,269.862966,7669.923354,1657.21347,5100.461544,3129.570512,4027.851047,389.962932,418.295648,...,348.580982,65.623858,-35.270229,-47.764228,-9.227144,48.909945,-26.765145,-49.083845,4106.441893,500.058697

Using prophet:

In [39]:
reg = HTSRegressor(model='prophet', revision_method='OLS')
reg = reg.fit(df=hierarchy_data, nodes=hierarchy)
preds_prophet = reg.predict(steps_ahead=0)

Fitting models: 100%|██████████████████████████████████████████████████████████████████| 14/14 [00:07<00:00,  1.94it/s]
INFO:hts.core.regressor:No arguments passed for 'steps_ahead', defaulting to predicting 1-step-ahead
Fitting models: 100%|██████████████████████████████████████████████████████████████████| 14/14 [00:17<00:00,  1.28s/it]
INFO:hts.core.regressor:Reconciling forecasts using <hts.revision.RevisionMethod object at 0x00000213F65119D0>

In [40]:
preds_prophet

,total,NT,CT,LIS,ALT,ALG,AÇR,MAD,NT_Alto_Minho,NT_Cávado,...,AÇR_Ilha_de_São_Miguel,AÇR_Ilha_Terceira,AÇR_Ilha_Graciosa,AÇR_Ilha_de_São_Jorge,AÇR_Ilha_do_Pico,AÇR_Ilha_do_Faial,AÇR_Ilha_das_Flores,AÇR_Ilha_do_Corvo,MAD_Ilha_da_Madeira,MAD_Ilha_de_Porto_Santo
2009-12-31,3407.073421,-919.992754,-3517.052835,13340.771013,-2701.382042,-1530.830134,-2677.590938,1413.151111,-1619.941548,-2041.007594,...,-597.388611,-277.059288,-376.395025,-390.431972,-406.698005,-323.956873,-388.129348,-389.275701,743.765605,-1663.758359
2010-12-31,5635.612818,-1888.474769,-4209.047671,17955.061857,-2905.016902,-430.648113,-4136.817405,1250.555820,-2232.807524,442.910841,...,-421.295159,-367.211456,-492.927103,-509.211094,-503.755913,-423.304090,-500.709076,-507.170521,831.036070,-2719.510839
2011-12-31,7812.746679,-2825.097368,-4877.227618,22421.475010,-3099.347184,643.174374,-5563.421091,1113.190556,-2826.469968,2874.177250,...,-246.316682,-455.220981,-606.049935,-624.545340,-597.829667,-519.760882,-609.878000,-621.656735,937.141582,-3762.238950
2012-12-31,4927.561931,-1776.959193,-3705.611167,15819.945609,-2428.937168,-169.958861,-3601.587406,790.670116,-1990.083246,509.445295,...,-403.869232,-305.258426,-431.063512,-440.705641,-442.243360,-377.506476,-439.749596,-442.784939,434.939689,-2211.898882
2013-12-31,7205.950337,-2776.687636,-4420.853906,20578.702042,-2641.611081,956.001771,-5092.395145,602.794292,-2621.712350,3044.542146,...,-226.762436,-397.480121,-550.916133,-562.837555,-542.208576,-479.670605,-555.654112,-563.998061,503.193737,-3279.881374
2014-12-31,9434.489735,-3745.169652,-5112.848742,25192.992890,-2845.245942,2056.183792,-6551.621612,440.199001,-3234.578326,5528.460580,...,-50.668984,-487.632289,-667.448211,-681.616676,-639.266484,-579.017823,-668.233840,-681.892881,590.464202,-4335.633854
2015-12-31,11611.623561,-4681.792228,-5781.028659,29659.406062,-3039.576196,3130.006296,-7978.225481,302.833767,-3828.240766,7959.726993,...,124.309496,-575.641811,-780.571040,-796.950919,-733.340234,-675.474611,-777.402761,-796.379092,696.569725,-5378.361953
2016-12-31,8726.438779,-3633.654031,-4609.412177,23057.876680,-2369.166152,2316.873079,-6016.391977,-19.686643,-2991.854040,5594.995042,...,-33.243050,-425.679253,-605.584613,-613.111216,-577.753924,-533.220202,-607.274353,-617.507293,194.367844,-3828.021874
2017-12-31,11004.827150,-4633.382451,-5324.654885,27816.633129,-2581.840037,3442.833728,-7507.199898,-207.562437,-3623.483140,8130.091896,...,143.863749,-517.900944,-725.437230,-735.243127,-677.719137,-635.384328,-723.178866,-738.720411,262.621903,-4896.004354
2018-12-31,13233.366513,-5601.864443,-6016.649690,32430.923993,-2785.474868,4543.015766,-8966.426547,-370.157697,-4236.349112,10614.010333,...,319.957204,-608.053109,-841.969305,-854.022245,-774.777042,-734.731542,-835.758591,-856.615228,349.892380,-5951.756823
2019-12-31,15410.500340,-6538.487019,-6684.829607,36897.337165,-2979.805121,5616.838269,-10393.030415,-507.522931,-4830.011553,13045.276744,...,494.935685,-696.062631,-955.092134,-969.356488,-868.850792,-831.188329,-944.927512,-971.101439,455.997903,-6994.484922
2020-12-31,12525.315558,-5490.348822,-5513.213125,30295.807781,-2309.395076,4803.705051,-8431.196911,-830.043341,-3993.624827,10680.544791,...,337.383138,-546.100072,-780.105707,-785.516785,-713.264482,-688.933921,-774.799104,-792.229640,-46.203979,-5444.144843
2021-12-31,6746.231553,-3049.802640,-3336.260794,17130.844157,-1314.357508,2542.102602,-4589.649729,-636.644534,-2291.167301,5146.501112,...,-8.452248,-278.521769,-443.980181,-437.905362,-421.548024,-409.457634,-447.373691,-450.917469,-367.176533,-2682.626107

Using auto_arima:

In [34]:
reg = HTSRegressor(model='auto_arima', revision_method='OLS')
reg = reg.fit(df=hierarchy_data, nodes=hierarchy)
preds_autoarima = reg.predict(steps_ahead=0)

Fitting models: 100%|██████████████████████████████████████████████████████████████████| 14/14 [00:09<00:00,  1.41it/s]
Fitting models: 100%|██████████████████████████████████████████████████████████████████| 14/14 [00:04<00:00,  3.13it/s]

In [35]:
preds_autoarima

,total,NT,CT,LIS,ALT,ALG,AÇR,MAD,NT_Alto_Minho,NT_Cávado,...,AÇR_Ilha_de_São_Miguel,AÇR_Ilha_Terceira,AÇR_Ilha_Graciosa,AÇR_Ilha_de_São_Jorge,AÇR_Ilha_do_Pico,AÇR_Ilha_do_Faial,AÇR_Ilha_das_Flores,AÇR_Ilha_do_Corvo,MAD_Ilha_da_Madeira,MAD_Ilha_de_Porto_Santo
2009-12-31,8190.044883,-2533.956415,7079.983612,23697.274412,-6546.773105,-4095.022441,-7094.963155,-2316.498025,-165.854802,137.319046,...,1235.345273,866.768900,703.803088,689.892172,689.892172,787.976588,702.481158,689.892172,1092.823848,-3626.780263
2010-12-31,7241.566227,-2175.629933,7889.006899,17235.851175,-5066.806063,-3054.380451,-6071.918372,-1514.557028,-290.456608,219.726659,...,958.765657,982.377797,843.258457,829.347540,829.347540,927.431957,835.742955,829.347540,1293.333271,-3468.963205
2011-12-31,7495.943020,-2315.899278,7667.715916,18660.408198,-5305.862335,-3181.524161,-6288.877206,-1740.018114,-290.273057,163.451402,...,994.549759,945.625061,810.172648,796.261731,796.261731,894.346148,813.935461,796.261731,1223.701158,-3539.600436
2012-12-31,7595.041806,-2338.279837,7586.471714,19078.347626,-5385.791381,-3155.421489,-6365.872396,-1824.412432,-275.887445,154.564790,...,1045.538823,944.812973,792.318064,778.407147,778.407147,876.491564,789.641787,778.407147,1193.316321,-3531.596158
2013-12-31,7584.210700,-2392.400844,7602.213298,19119.550907,-5387.088642,-3175.027697,-6368.628373,-1814.407948,-245.985511,143.672441,...,1109.431779,927.824286,787.407586,773.496669,773.496669,871.581086,787.941966,773.496669,1192.114282,-3584.515126
2014-12-31,15635.690403,-2199.218957,8176.251796,20584.459367,-5067.799140,1173.233703,-5799.789858,-1231.446508,109.538396,194.091384,...,1232.806175,999.000700,842.032682,828.121765,828.121765,926.206182,839.679081,828.121765,1252.890813,-3452.109770
2015-12-31,19702.468155,-3148.368426,6328.742516,25998.980248,-2823.000870,2789.440301,-6778.464536,-2664.861078,-531.884824,-446.312174,...,1627.074138,711.449238,558.015865,544.104948,586.250954,642.189365,547.408197,544.104948,785.515668,-3933.884094
2016-12-31,21087.343330,-3258.564052,6013.776389,27144.727058,-2400.420174,3383.039355,-6892.286188,-2902.929058,-596.086534,-499.681877,...,1622.299688,680.684074,516.186188,502.275271,551.204214,600.359688,512.176806,502.275271,708.370540,-3966.934592
2017-12-31,22681.657767,-3446.620340,5625.044372,28760.638626,-2020.874791,4001.315923,-7022.707043,-3215.138981,-694.197219,-556.204816,...,1560.841231,731.639931,461.829245,447.918329,504.551599,546.002745,452.384718,447.918329,590.202350,-4036.822689
2018-12-31,24779.375415,-3604.335080,5210.104188,30432.673872,-1616.462639,5096.294935,-7196.406056,-3542.493805,-776.048574,-631.868926,...,1527.320518,654.403607,417.132734,403.221817,464.109298,501.306234,412.126430,403.221817,518.384517,-4122.719596
2019-12-31,25702.328877,-3665.561773,5018.507297,31022.516940,-1209.736783,5351.340260,-7140.386484,-3674.350580,-855.538516,-666.014530,...,1434.651573,645.388655,396.184396,382.273480,473.005881,480.357896,418.058538,382.273480,489.954326,-4155.516099
2020-12-31,26920.154577,-3724.928134,4782.550226,31655.795348,-628.329430,5873.612268,-7226.782493,-3811.763207,-985.639472,-724.933130,...,1337.766195,606.925252,384.344868,370.433952,464.454972,468.518368,385.198799,370.433952,472.851529,-4197.779663
2021-12-31,12598.861879,-2450.126819,7125.822811,19561.421771,-3206.022305,-239.597824,-6256.238538,-1936.397216,-451.968111,-189.244779,...,702.693425,791.301620,791.465166,777.554249,811.514832,875.638666,796.506437,777.554249,1225.310755,-3675.437574